version: '3.8'

services:
  # Banco de Dados Postgres
  postgres:
    image: postgres:15
    container_name: crescix_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432" # Para vocÃª acessar via DBeaver se precisar
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - crescix-network

  # Cache para a Evolution API
  redis:
    image: redis:7-alpine
    container_name: evolution_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - crescix-network

  # Evolution API
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution_api
    environment:
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY}
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_CLIENT=postgresql
      - DATABASE_TYPE=postgres
      - DATABASE_CONNECTION_URI=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://default:${REDIS_PASSWORD}@redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - crescix-network

  # Backend CrescIX
  crescix-backend:
    build: .
    container_name: crescix_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - postgres
      - evolution-api
    networks:
      - crescix-network

networks:
  crescix-network:
    driver: bridge